import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import http from "node:http";
import type { ExtractionResult, DesignReport } from "../core/types.js";
import type { FusionReport } from "../core/fuse.js";
import { blendTokens } from "../core/fuse.js";
import { LlmClient } from "../llm/client.js";

const SYSTEM = `You are an expert front-end engineer. You generate a single-file React
homepage (default export) that recreates the VISUAL STYLE of a reference site as an
ORIGINAL same-style page. You output ONLY JSON. The component must be self-contained,
use inline Tailwind utility classes, and not import anything except React. Use the
provided design tokens (colors, fonts, radii) faithfully. Recreate the section rhythm
from the topology. Use placeholder text in the same language/topic, and reference local
asset paths under /assets/ for any images you include. Keep it production-clean.`;

interface GenResult {
  pageTsx: string;
  globalsCss: string;
}

export async function buildSite(
  outDir: string,
  x: ExtractionResult,
  r: DesignReport,
  llm: LlmClient,
  onStep: (m: string) => void,
  instructions?: string
): Promise<void> {
  onStep("Asking the model to compose a same-style page");
  const slim = {
    title: x.title,
    lang: x.lang,
    tokens: {
      bg: x.tokens.bodyBackground,
      fg: x.tokens.bodyColor,
      palette: x.tokens.palette.slice(0, 10),
      fonts: x.tokens.fontFamilies.slice(0, 4),
      googleFonts: x.tokens.googleFonts,
      radii: x.tokens.radii,
      headingSizes: x.tokens.headingSizes,
    },
    sections: x.sections.map((s) => ({
      name: s.name,
      layout: s.layout,
      interaction: s.interaction,
      text: s.textPreview,
    })),
    vibe: r.vibe,
    summary: r.summary,
  };

  const extra = instructions && instructions.trim()
    ? `\n\nUSER CUSTOMIZATION (apply these; do NOT copy the original text/brand verbatim):\n${instructions.trim()}`
    : "\n\nUse fresh placeholder copy in the same language/topic; do not copy the original's exact wording or brand names.";

  const user = `Reference design (style only, build an ORIGINAL same-style homepage):
${JSON.stringify(slim, null, 2)}${extra}

Return JSON:
{
  "pageTsx": "full source of src/app/page.tsx (a default-exported React component, 'use client' at top, inline Tailwind classes, recreating the sections + style)",
  "globalsCss": "contents of src/app/globals.css starting with @import \"tailwindcss\"; plus :root css variables for the extracted colors and any @font-face/keyframes"
}`;

  const gen = await llm.json<GenResult>(SYSTEM, user);

  onStep("Scaffolding Next.js project");
  scaffold(outDir, x, gen);

  onStep("Downloading reference assets");
  await downloadAssets(outDir, x, onStep);
}

function scaffold(outDir: string, x: ExtractionResult, gen: GenResult) {
  const w = (rel: string, content: string) => {
    const p = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content, { encoding: "utf8" });
  };

  w("package.json", JSON.stringify({
    name: "designforge-output",
    version: "0.1.0",
    private: true,
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies: { next: "^15.1.6", react: "^19.0.0", "react-dom": "^19.0.0" },
    devDependencies: {
      typescript: "^5.7.3",
      "@types/node": "^22.10.7",
      "@types/react": "^19.0.7",
      "@types/react-dom": "^19.0.3",
      tailwindcss: "^4.0.0",
      "@tailwindcss/postcss": "^4.0.0",
      postcss: "^8.5.1",
    },
  }, null, 2));

  w("tsconfig.json", JSON.stringify({
    compilerOptions: {
      target: "ES2017", lib: ["dom", "dom.iterable", "esnext"], allowJs: true,
      skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true,
      module: "esnext", moduleResolution: "bundler", resolveJsonModule: true,
      isolatedModules: true, jsx: "preserve", incremental: true,
      plugins: [{ name: "next" }], baseUrl: ".", paths: { "@/*": ["./src/*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  }, null, 2));

  w("postcss.config.mjs", "const config = { plugins: [\"@tailwindcss/postcss\"] };\nexport default config;\n");
  w("next.config.ts", "import type { NextConfig } from \"next\";\nconst nextConfig: NextConfig = { reactStrictMode: true };\nexport default nextConfig;\n");
  w("next-env.d.ts", "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n");
  w(".gitignore", "node_modules\n.next\nout\n");

  const layout = `import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = { title: ${JSON.stringify(x.title || "Same-style site")}, description: "Generated by designforge" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (<html lang=${JSON.stringify(x.lang || "en")}><body>{children}</body></html>);
}
`;
  w("src/app/layout.tsx", layout);
  w("src/app/page.tsx", gen.pageTsx);
  w("src/app/globals.css", gen.globalsCss);

  // build report alongside
  w("DESIGNFORGE.md", "# Generated by designforge\n\nStyle reference: " + x.finalUrl + "\n\nRun: npm install && npm run dev\n");
}

async function downloadAssets(
  outDir: string,
  x: ExtractionResult,
  onStep: (m: string) => void
) {
  const dir = path.join(outDir, "public", "assets");
  fs.mkdirSync(dir, { recursive: true });
  const imgs = x.assets
    .filter((a) => a.kind === "image" || a.kind === "background")
    .slice(0, 20);
  let ok = 0;
  for (const a of imgs) {
    try {
      const name = a.src.split("?")[0].split("/").pop() || "asset";
      await download(a.src, path.join(dir, name), x.finalUrl);
      ok++;
    } catch {
      /* skip */
    }
  }
  onStep(`Downloaded ${ok}/${imgs.length} reference images`);
}

function download(url: string, dest: string, referer: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith("https") ? https : http;
    const req = mod.get(
      url,
      { headers: { Referer: referer, "User-Agent": "Mozilla/5.0" } },
      (res) => {
        if (res.statusCode && res.statusCode >= 400) {
          res.resume();
          return reject(new Error("HTTP " + res.statusCode));
        }
        const file = fs.createWriteStream(dest);
        res.pipe(file);
        file.on("finish", () => file.close(() => resolve()));
      }
    );
    req.on("error", reject);
    req.setTimeout(20000, () => req.destroy(new Error("timeout")));
  });
}


export async function buildFusionSite(
  outDir: string,
  a: ExtractionResult,
  bSite: ExtractionResult,
  weightA: number,
  report: FusionReport,
  llm: LlmClient,
  onStep: (m: string) => void,
  instructions?: string
): Promise<void> {
  onStep("Composing a fused same-style page");
  const blend = blendTokens(a, bSite, weightA);
  const slim = {
    weight: { siteA: Math.round(weightA), siteB: 100 - Math.round(weightA) },
    siteA: { title: a.title, bg: a.tokens.bodyBackground, palette: a.tokens.palette.slice(0, 6), fonts: a.tokens.fontFamilies.slice(0, 2), sections: a.sections.map((s) => s.name).slice(0, 8) },
    siteB: { title: bSite.title, bg: bSite.tokens.bodyBackground, palette: bSite.tokens.palette.slice(0, 6), fonts: bSite.tokens.fontFamilies.slice(0, 2), sections: bSite.sections.map((s) => s.name).slice(0, 8) },
    blendedTokens: blend,
    fusionPlan: { vibe: report.vibe, colorPlan: report.colorPlan, typographyPlan: report.typographyPlan, layoutPlan: report.layoutPlan },
  };
  const extra = instructions && instructions.trim()
    ? `\n\nUSER CUSTOMIZATION:\n${instructions.trim()}`
    : "\n\nUse fresh original placeholder copy; do not copy either site's exact wording or brand.";
  const user = `Build ONE original homepage that FUSES the two reference sites below,
honoring the blend weight. Use the blendedTokens as the basis for color/fonts.
${JSON.stringify(slim, null, 2)}${extra}

Return JSON:
{
  "pageTsx": "full src/app/page.tsx (default-exported React component, 'use client', inline Tailwind classes, fused sections + style)",
  "globalsCss": "src/app/globals.css starting with @import \"tailwindcss\"; plus :root variables for the blended colors and any keyframes"
}`;
  const gen = await llm.json<{ pageTsx: string; globalsCss: string }>(SYSTEM, user);

  onStep("Scaffolding Next.js project");
  const merged: ExtractionResult = {
    ...a,
    title: a.title + " x " + bSite.title,
    assets: [...a.assets, ...bSite.assets],
  };
  scaffold(outDir, merged, gen);

  onStep("Downloading reference assets");
  await downloadAssets(outDir, merged, onStep);
}
